#!/usr/bin/env python
import sys
import os
import shutil

# use only for organised data

# In[ ]:


def usage():
    sys.exit('Usage:\nInput arguement <Base_dir>\nChanges the name of aasana folders as SubjID_aasanaID\nUse only for organised data')
if(len(sys.argv)!=2):
    usage()
basedir = sys.argv[1]
outputdir = os.getcwd()
os.chdir(basedir)
list_of_subjects = next(os.walk(os.getcwd()))[1]
for subject in list_of_subjects:
    os.chdir(subject)
    list_of_aasanas = next(os.walk(os.getcwd()))[1]
    for aasana in list_of_aasanas:
        aasana_split =aasana.split('_')
        new_name = ''
        for i in range(1,len(aasana_split)):
            new_name = new_name+aasana_split[i]
        new_name = subject+'_'+new_name
        shutil.move(aasana,new_name)
    os.chdir('..')

